title: Kafka Streams
description: "Применение Kafka Streams для обработки потоковых данных. Основные концепции, примеры и сравнение с ksqlDB."
show_downloads: true
remote_theme: pages-themes/architect@v0.2.0 # depending on the selected theme
plugins:
  - jekyll-remote-theme
